services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./database.prod.sqlite:/app/database.prod.sqlite
