version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - ./database.prod.sqlite:/app/database.prod.sqlite
      
  # Uncomment this section if you want to use MariaDB
  # db:
  #   image: mariadb:latest
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'root'
  #     MYSQL_DATABASE: 'CrossFitObernai'
  #   volumes:
  #     - ../data:/var/lib
  #   ports:
  #     - '3306:3306'
